### ISSUE TITLE
CI takes makes longer than it needs to

### ISSUE THREAD

**Issue by chriszs** [biglocalnews/warn-scraper#414]
CI takes about 5 minutes. Roughly 4 of those minutes appear to be Python/pipenv setup (2 minutes per step). I switched to the official Python setup action with built in catching over on the bot repo and it now takes 7 seconds (so about 14 seconds total, maybe).

Why is this important? Because when you get CI feedback on builds faster, you can iterate on PRs much faster.

This is how I did it:
```yaml
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pipenv'
      - run: pipenv install
```
